correctly serialize MTOM into axios data
vpulim/node-soap pull request #1173
Opened 2021-11-12 16:15 UTC by ischisan

2021-11-12 16:17 UTC, ischisan commented
content was empty when using MTOM and Content-Lenfth was 0, so i added the logic for serializing the multiparts into the body.

2021-11-12 16:59 UTC, jsdevel commented
please undo all the style changes

2021-11-12 17:39 UTC, ischisan commented
> please undo all the style changes. i can't even see what you changed with all the whitespace changes...

sorry, prettier was activated ;-)

i removed the style changes.

BR

2021-11-13 10:21 UTC, ischisan commented
I added support to enforce gzip compression in soap request

2021-11-16 16:15 UTC, jsdevel requested changes

2021-11-16 16:15 UTC, jsdevel commented on Readme.md
> +* `forceGzip`: set to True if you ant to force transfer-encoding in gzip (default: ```false```)
ant -> want

2021-11-16 16:15 UTC, jsdevel commented on Readme.md
> +* `forceGzip`: set to True if you ant to force transfer-encoding in gzip (default: ```false```)
ant -> want

2021-11-16 17:04 UTC, jsdevel commented
please ensure the build passes

2021-11-16 17:04 UTC, jsdevel approved these changes

2021-11-16 17:19 UTC, ischisan commented
> @ischisan do you have a way of adding a test for this?

this is hardly possible when the soap server does not support MTOM. Maybe I can add that server functionality later, but not before next month. I would provide a test for server and client after that.

2021-11-16 19:36 UTC, merged

2021-11-16 19:37 UTC, jsdevel commented
that would be great if you could follow up when you can @ischisan