Fix names only in soap messages.
vpulim/node-soap pull request #1205
Opened 2022-12-06 22:09 UTC by alex-eri

Without namespace check this function fails with `Exception has occurred: TypeError: Cannot read properties of undefined (reading 'description')` if Message>Body tags deepper inside answer.

2024-07-17 07:00 UTC, pestig approved these changes
I had a same problem with deep Body tag. It's fixed my problem also.

2024-07-17 07:14 UTC, w666 commented
Hi @alex-eri @pestig 

I am happy to merge it and include into next release, it just requires a test. If you can add one that would be great.

2024-08-07 09:23 UTC, w666 requested changes
Please add a unit test

2025-07-09 08:39 UTC, w666 commented
I rebased this, but some tests failed. I was about to approve it without a test but seems like this change breaks something.

2025-07-10 02:30 UTC, smokhov commented
Weird. Those appear timeout errors though. Possible infra issues of GitHub? Maybe can simply re-run the job in GitHub's GUI?

2025-07-16 07:38 UTC, w666 commented
The test suite is a bit weird, it does log errors as timeouts, debugging it is a kinda pita.

2025-07-17 21:23 UTC, smokhov commented
it seems the errors are in `WSSecurityPlusCert.ts`. When running `npm cover` locally I get the same exact errors even without the change proposed here by removing it.

2025-07-18 14:04 UTC, smokhov commented
Very weird. Now most tests on my local system pass. It went down from 11  to 1 (`WSSecurityCert` rsa-sha1), then to 2 not passing ("before all" hook for "lastElapsedTime is computed"). And this includes master without the proposed change. It seems almost each time I run `npm run cover` the numer of tests failing changes. Something is off here...

I get no more time out errors (previously I tried with the timeout settings, as well as catcbing `done` (per [this post](https://stackoverflow.com/questions/44149096/for-async-tests-and-hooks-ensure-done-is-called-if-returning-a-promise-en)), but that led to more errors that I could not make sense of.

My current failures locally are:

```
  587 passing (3s)
  2 pending
  2 failing

  1) SOAP Client
       "before all" hook for "lastElapsedTime is computed":
     Uncaught Error: listen EADDRINUSE: address already in use :::54454
      at Server.setupListenHandle [as _listen2] (node:net:1908:16)
      at listenInCluster (node:net:1965:12)
      at Server.listen (node:net:2067:7)
      at Context.<anonymous> (test/client-response-options-test.js:33:12)
      at process.processImmediate (node:internal/timers:483:21)

  2) WSSecurityCert
       should use rsa-sha1 signature method when the signatureAlgorithm option is set to WSSecurityCert:
     Error: error:03000098:digital envelope routines::invalid digest
      at Sign.sign (node:internal/crypto/sig:128:29)
      at /home/serguei/mdreams/node-soap/node_modules/xml-crypto/lib/signature-algorithms.js:11:32
      at RsaSha1.getSignature (node_modules/xml-crypto/lib/types.js:52:20)
      at SignedXml.calculateSignatureValue (node_modules/xml-crypto/lib/signed-xml.js:327:42)
      at SignedXml.computeSignature (node_modules/xml-crypto/lib/signed-xml.js:763:18)
      at WSSecurityCert.postProcess (lib/security/WSSecurityCert.js:2:10622)
      at Context.<anonymous> (test/security/WSSecurityCert.js:285:26)
      at process.processImmediate (node:internal/timers:483:21)
```

but yesterday (1) was not there. And I changed nothing in this instance... (2) may be related to the recent update of `xml-crypto` in 0b159d17ab47869a40625657c2dee9415c4fc207 but that should have been caught sooner than now.

2025-07-22 08:26 UTC, w666 commented
@smokhov 

Well, tests on main are fairly stable. This branch never worked for me.

2025-08-04 08:12 UTC, closed without merging