Pass the error object to log
vpulim/node-soap pull request #1246
Opened 2024-07-18 20:55 UTC by ikonst

The current code uses `suppressStack` to determine what is logged, while I think `suppressStack` was only intended to control whether we expose internals to the caller.

It would be preferable if the logging mechanism could see the original error for what it is, since then it could use the appropriate logging mechanism in the code base; for example, pass the error object to Sentry, or log it in a structured way (name and stack separately) [for Datadog to consume](https://docs.datadoghq.com/standard-attributes/), etc.

2024-07-19 08:08 UTC, w666 commented
Hi @ikonst,

Could you please add a test for this? Change looks good me.

2024-07-19 17:24 UTC, ikonst commented
@w666 take a look ^

2024-07-20 23:53 UTC, w666 commented on test/server-test.js
> +        // assert.notStrictEqual(test.logMessages[0].tyoe, {});
I guess this and two lines above were used for debugging?  It would be good to remove unused code to keep it clean.

2024-07-20 23:53 UTC, w666 requested changes
One minor comment, otherwise looks good to me.

2024-07-21 07:53 UTC, w666 approved these changes

2024-07-21 07:53 UTC, w666 approved these changes

2024-07-21 07:55 UTC, w666 commented
Approved, thanks for the improvement, I will include it into next release. 

Please let me know if you need these changes asap, will see if I can make a release earlier.

2024-07-21 09:06 UTC, ikonst commented
Thank you. There's no urgency.

2024-08-04 06:48 UTC, merged